# Generated by Django 4.1.3 on 2022-11-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_shoelace'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoelace',
            name='color',
            field=models.TextField(default='red'),
        ),
        migrations.AddField(
            model_name='shoelace',
            name='date',
            field=models.DateField(default='2022-11-15'),
        ),
    ]
