# Generated by Django 4.1.3 on 2022-11-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_brand_cleaned_delete_shoelace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoelace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.AlterField(
            model_name='cleaned',
            name='product',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='sneaker',
            name='shoelaces',
            field=models.ManyToManyField(to='main_app.shoelace'),
        ),
    ]
