# Generated by Django 4.1.3 on 2022-11-20 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_shoelace_delete_brand_alter_cleaned_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoelace',
            name='name',
        ),
    ]
